---
booktitle: Proceedings of the 6th Symposium on Advances in Approximate Bayesian Inference
shortname: AABI
year: '2024'
volume: '253'
start: &1 2024-07-21
end: 2024-07-21
published: 2024-07-29
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: aabi24
month: 0
cycles: false
bibtex_editor: Antor\'{a}n, Javier and Naesseth, Christian A.
editor:
- given: Javier
  family: Antorán
- given: Christian A.
  family: Naesseth
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the 6th Symposium on Advances in Approximate Bayesian Inference
    Held in Vienna, Austria on 21 July 2024

  Published as Volume 253 by the Proceedings of Machine Learning Research on 29 July 2024.

  Volume Edited by:
    Javier Antorán
    Christian A. Naesseth

  Series Editors:
    Neil D. Lawrence
date_str: 21 Jul
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v253"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v253
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v253
email: ''
conference:
  name: Symposium on Advances in Approximate Bayesian Inference
  url: https://approximateinference.org
  location: Vienna, Austria
  dates:
  - *1
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v253/aabi24.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v253/aabi24.bib
